// <auto-generated />
using System;
using ChatManagement.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatManagement.DataAccess.Migrations
{
    [DbContext(typeof(ChatManagementDbContext))]
    partial class ChatManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatManagement.Domain.Models.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67cf8250-220e-4bd7-9d25-4ea480617e49"),
                            CreatedAt = new DateTime(2024, 8, 22, 22, 35, 3, 67, DateTimeKind.Local).AddTicks(7563),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Chat 1",
                            UserIds = "[\"58c58ff5-aeba-43e9-bf88-20fe29ae5ac2\"]"
                        },
                        new
                        {
                            Id = new Guid("8ba44e3b-8164-450a-ab84-06e4d6add351"),
                            CreatedAt = new DateTime(2024, 8, 22, 22, 35, 3, 67, DateTimeKind.Local).AddTicks(7629),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Chat 2",
                            UserIds = "[\"dd3ced32-c87e-4146-a423-f5a7e59574b2\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
